/*
 * generated by Xtext
 */
package at.bestsolution.typescript.service.spec.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import at.bestsolution.typescript.service.spec.ui.internal.TSSpecActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TSSpecExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return TSSpecActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return TSSpecActivator.getInstance().getInjector(TSSpecActivator.AT_BESTSOLUTION_TYPESCRIPT_SERVICE_SPEC_TSSPEC);
	}
	
}
