/*
 * generated by Xtext
 */
package at.bestsolution.typescript.service.spec.ui.contentassist

import at.bestsolution.typescript.service.spec.ui.contentassist.AbstractTSSpecProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class TSSpecProposalProvider extends AbstractTSSpecProposalProvider {
}
