/*
 * generated by Xtext
 */
package at.bestsolution.typescript.service.spec.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import at.bestsolution.typescript.service.spec.services.TSSpecGrammarAccess;

public class TSSpecParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private TSSpecGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected at.bestsolution.typescript.service.spec.parser.antlr.internal.InternalTSSpecParser createParser(XtextTokenStream stream) {
		return new at.bestsolution.typescript.service.spec.parser.antlr.internal.InternalTSSpecParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "ServiceDefs";
	}
	
	public TSSpecGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(TSSpecGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
