/*
 * generated by Xtext
 */
package at.bestsolution.typescript.service.spec.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TSSpecAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("at/bestsolution/typescript/service/spec/parser/antlr/internal/InternalTSSpec.tokens");
	}
}
