/*
 * generated by Xtext
 */
package at.bestsolution.typescript.service.spec;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TSSpecRuntimeModule extends at.bestsolution.typescript.service.spec.AbstractTSSpecRuntimeModule {

}
