/*
 * generated by Xtext
 */
package at.bestsolution.typescript.service.spec;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class TSSpecStandaloneSetup extends TSSpecStandaloneSetupGenerated{

	public static void doSetup() {
		new TSSpecStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

