/*
 * generated by Xtext
 */
package at.bestsolution.typescript.service.spec.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TSSpecUiModule extends at.bestsolution.typescript.service.spec.ui.AbstractTSSpecUiModule {
	public TSSpecUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
