package at.bestsolution.typescript.service.api.model;

public interface CompilerOptions  {
	public boolean allowNonTsExtensions();
	public String charset();
	public boolean declaration();
	public boolean diagnostics();
	public boolean emitBOM();
	public boolean help();
	public boolean init();
	public boolean inlineSourceMap();
	public boolean inlineSources();
	public boolean jsx();
	public boolean listFiles();
	public String locale();
	public String mapRoot();
	public boolean noEmit();
	public boolean noEmitHelpers();
	public boolean noEmitOnError();
	public boolean noErrorTruncation();
	public boolean noImplicitAny();
	public boolean noLib();
	public boolean noResolve();
	public String out();
	public String outFile();
	public String outDir();
	public boolean preserveConstEnums();
	public String project();
	public boolean removeComments();
	public String rootDir();
	public boolean sourceMap();
	public String sourceRoot();
	public boolean suppressExcessPropertyErrors();
	public boolean suppressImplicitAnyIndexErrors();
	public boolean version();
	public boolean watch();
	public boolean isolatedModules();
	public boolean experimentalDecorators();
	public boolean emitDecoratorMetadata();

	public interface Builder {
		public Builder charset( String value );
		public Builder declaration( boolean value );
		public Builder diagnostics( boolean value );
		public Builder emitBOM( boolean value );
		public Builder help( boolean value );
		public Builder init( boolean value );
		public Builder inlineSourceMap( boolean value );
		public Builder inlineSources( boolean value );
		public Builder jsx( boolean value );
		public Builder listFiles( boolean value );
		public Builder locale( String value );
		public Builder mapRoot( String value );
		public Builder noEmit( boolean value );
		public Builder noEmitHelpers( boolean value );
		public Builder noEmitOnError( boolean value );
		public Builder noErrorTruncation( boolean value );
		public Builder noImplicitAny( boolean value );
		public Builder noLib( boolean value );
		public Builder noResolve( boolean value );
		public Builder out( String value );
		public Builder outFile( String value );
		public Builder outDir( String value );
		public Builder preserveConstEnums( boolean value );
		public Builder project( String value );
		public Builder removeComments( boolean value );
		public Builder rootDir( String value );
		public Builder sourceMap( boolean value );
		public Builder sourceRoot( String value );
		public Builder suppressExcessPropertyErrors( boolean value );
		public Builder suppressImplicitAnyIndexErrors( boolean value );
		public Builder version( boolean value );
		public Builder watch( boolean value );
		public Builder isolatedModules( boolean value );
		public Builder experimentalDecorators( boolean value );
		public Builder emitDecoratorMetadata( boolean value );
		public CompilerOptions build();
	}
}
